<?php

/**
 * @file
 * Install, update and uninstall functions for bt_crm_potential_client.
 */

use Drupal\path_alias\Entity\PathAlias;

/**
 * Implements hook_install().
 */
function bt_crm_potential_client_install() {
  // Add path alias.
  $path_alias = PathAlias::create([
    'path' => '/app/contacts/add/person/bt_potential_client',
    'alias' => '/app/contacts/add/person/potential-client',
    'langcode' => 'en',
  ]);
  $path_alias->save();
}
