<?php

/**
 * @file
 * Contains bt_crm_potential_client.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function bt_crm_potential_client_help($route_name) {
  switch ($route_name) {
    // Main module help for the bt_crm_potential_client module.
    case 'help.page.bt_crm_potential_client':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Btester CRM Client') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bt_crm_potential_client_theme() {
  return [
    'bt_crm_potential_client' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function bt_crm_potential_client_redhen_contact_insert(EntityInterface $entity) {
  // Convert to lowercase, trim spaces,
  // replace spaces with underscore and then truncate to 60 chars.
  $pathTitle = substr(str_replace(" ", "-", trim(strtolower($entity->label()))), 0, 60);
  if ($entity->bundle() == 'bt_potential_client') {
    \Drupal::service('path.alias_storage')->save("/app/contacts/persons/" . $entity->id(), "/app/contacts/persons/potential-client/" . $pathTitle, "en");
    \Drupal::service('path.alias_storage')->save("/app/contacts/persons/" . $entity->id() . '/edit', "/app/contacts/persons/potential-client/" . $pathTitle . '/edit', "en");
    \Drupal::service('path.alias_storage')->save("/app/contacts/persons/" . $entity->id() . '/delete', "/app/contacts/persons/potential-client/" . $pathTitle . '/delete', "en");
  }
}
