<?php

/**
 * @file
 * Install, update and uninstall functions for bt_crm_company.
 */

use Drupal\path_alias\Entity\PathAlias;

/**
 * Implements hook_install().
 */
function bt_crm_company_install() {
  // Add path alias.
  $path_alias = PathAlias::create([
    'path' => '/app/contacts/add/organization/bt_company',
    'alias' => '/app/contacts/add/organization/company',
  ]);
  $path_alias->save();
}
