<?php

/**
 * @file
 * Contains bt_crm_supplier.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function bt_crm_supplier_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bt_crm_supplier module.
    case 'help.page.bt_crm_supplier':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Btester CRM Client') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bt_crm_supplier_theme() {
  return [
    'bt_crm_supplier' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function bt_crm_supplier_redhen_org_insert(EntityInterface $entity) {
    // Convert to lowercase, trim spaces, replace spaces with underscore and then truncate to 60 chars.
    $pathTitle = substr(str_replace(" ","-",trim(strtolower($entity->label()))),0,60);

    if ($entity->bundle() == 'bt_supplier') {
        \Drupal::service('path.alias_storage')->save("/app/contacts/organization/" . $entity->id(), "/app/contacts/organization/supplier/" . $pathTitle, "en");
        \Drupal::service('path.alias_storage')->save("/app/contacts/organization/" . $entity->id() . '/edit', "/app/contacts/organization/supplier/" . $pathTitle . '/edit', "en");
        \Drupal::service('path.alias_storage')->save("/app/contacts/organization/" . $entity->id() . '/delete', "/app/contacts/organization/supplier/" . $pathTitle . '/delete', "en");
    }
}