<?php

/**
 * @file
 * Install, update and uninstall functions for bt_crm_contact.
 */

use Drupal\path_alias\Entity\PathAlias;

/**
 * Implements hook_install().
 */
function bt_crm_contact_install() {
  // Add path alias.
  $path_alias = PathAlias::create([
    'path' => '/app/contacts/add/person/bt_contact',
    'alias' => '/app/contacts/add/person/contact',
    'langcode' => 'en',
  ]);
  $path_alias->save();
}
