<?php

/**
 * @file
 * Contains bt_crm_contact.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\path_alias\Entity\PathAlias;

/**
 * Implements hook_help().
 */
function bt_crm_contact_help($route_name) {
  switch ($route_name) {
    // Main module help for the bt_crm_contact module.
    case 'help.page.bt_crm_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Btester CRM Client') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bt_crm_contact_theme() {
  return [
    'bt_crm_contact' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function bt_crm_contact_redhen_contact_insert(EntityInterface $entity) {
  // Convert to lowercase, trim spaces,
  // replace spaces with underscore and then truncate to 60 chars.
  $pathTitle = substr(str_replace(" ", "-", trim(strtolower($entity->label()))), 0, 60);
  if ($entity->bundle() == 'bt_contact') {
    $path_alias = PathAlias::create([
      'path' => "/app/contacts/persons/" . $entity->id(),
      'alias' => "/app/contacts/persons/contact/" . $pathTitle,
    ]);
    $path_alias->save();

    $path_alias = PathAlias::create([
      'path' => "/app/contacts/persons/" . $entity->id() . "/edit",
      'alias' => "/app/contacts/persons/contact/" . $pathTitle . "/edit",
    ]);
    $path_alias->save();

    $path_alias = PathAlias::create([
      'path' => "/app/contacts/persons/" . $entity->id() . "/delete",
      'alias' => "/app/contacts/persons/contact/" . $pathTitle . "/delete",
    ]);
    $path_alias->save();
  }
}
